"use client"

import { useState, useMemo } from "react"
import { news, newsCategories, NewsCategory } from "@/data/news"
import { MathRain } from "@/components/MathRain"
import { NavBar } from "@/components/NavBar"
import Link from "next/link"

const btnBase:React.CSSProperties = {fontFamily:"'JetBrains Mono',monospace",fontSize:11,fontWeight:700,padding:'5px 14px',border:'1px solid #1a1a1a',color:'#888',background:'transparent',cursor:'pointer',transition:'0.2s',borderRadius:6}
const btnSel:React.CSSProperties = {...btnBase,borderColor:'#7a6230',color:'#e8c96a',background:'rgba(201,168,76,0.08)'}

export default function NewsPage() {
  const [cat, setCat] = useState<NewsCategory|null>(null)
  const [src, setSrc] = useState<"all"|"agent"|"user">("all")

  const filtered = useMemo(()=>{
    let r=news;if(cat)r=r.filter(n=>n.category===cat)
    if(src==="agent")r=r.filter(n=>n.isAutoGenerated);if(src==="user")r=r.filter(n=>!n.isAutoGenerated)
    return r.sort((a,b)=>new Date(b.publishedAt).getTime()-new Date(a.publishedAt).getTime())
  },[cat,src])

  return (
    <div style={{background:'#000',minHeight:'100vh',fontFamily:"'Noto Sans SC', sans-serif",position:'relative',overflow:'hidden'}}>
      <MathRain />
      <NavBar />

      <div style={{maxWidth:900,margin:'0 auto',padding:'60px 60px',position:'relative',zIndex:10,background:'rgba(0,0,0,0.85)'}} className="max-sm:px-4">
        <p style={{fontFamily:"'JetBrains Mono',monospace",fontSize:10,letterSpacing:'0.4em',color:'#7a6230',textTransform:'uppercase',marginBottom:10,fontWeight:700}}>News Feed</p>
        <h1 style={{fontSize:36,fontWeight:900,color:'#fff',letterSpacing:'0.02em',marginBottom:8}}>AI 资讯</h1>
        <p style={{fontSize:14,fontWeight:400,color:'#ccc',marginBottom:40}}>Maintained by Agent + Community</p>

        <div style={{display:'flex',gap:28,marginBottom:40,flexWrap:'wrap'}}>
          <div>
            <p style={{fontFamily:"'JetBrains Mono',monospace",fontSize:10,letterSpacing:'0.2em',color:'#ccc',fontWeight:700,marginBottom:10}}>SOURCE</p>
            <div style={{display:'flex',gap:6}}>
              {(["all","agent","user"]as const).map(f=><button key={f} onClick={()=>setSrc(f)} style={src===f?btnSel:btnBase}>{f==="all"?"ALL":f.toUpperCase()}</button>)}
            </div>
          </div>
          <div>
            <p style={{fontFamily:"'JetBrains Mono',monospace",fontSize:10,letterSpacing:'0.2em',color:'#ccc',fontWeight:700,marginBottom:10}}>CATEGORY</p>
            <div style={{display:'flex',flexWrap:'wrap',gap:6}}>
              <button onClick={()=>setCat(null)} style={cat===null?btnSel:btnBase}>ALL</button>
              {newsCategories.map(c=><button key={c.key} onClick={()=>setCat(cat===c.key?null:c.key)} style={cat===c.key?btnSel:btnBase}>{c.label}</button>)}
            </div>
          </div>
        </div>

        <p style={{fontFamily:"'JetBrains Mono',monospace",fontSize:11,fontWeight:700,color:'#ccc',marginBottom:24}}>{filtered.length} articles</p>

        {filtered.length===0?(
          <div style={{textAlign:'center',padding:80,fontSize:14,fontWeight:500,color:'#aaa'}}>No articles</div>
        ):(
          <div style={{display:'flex',flexDirection:'column',gap:10}}>
            {filtered.map((n,i)=>(
              <a key={n.id} href={n.url} target="_blank" rel="noopener noreferrer"
                style={{background:'rgba(255,255,255,0.03)',border:'1px solid #1a1a1a',borderRadius:16,padding:'28px 32px',textDecoration:'none',transition:'all 0.3s'}}
                onMouseEnter={e=>{e.currentTarget.style.background='rgba(201,168,76,0.06)';e.currentTarget.style.borderColor='#7a6230'}}
                onMouseLeave={e=>{e.currentTarget.style.background='rgba(255,255,255,0.03)';e.currentTarget.style.borderColor='#1a1a1a'}}>
                <div style={{display:'flex',alignItems:'center',gap:10,marginBottom:12,fontFamily:"'JetBrains Mono',monospace",fontSize:10,fontWeight:700,color:'#aaa',letterSpacing:'0.05em'}}>
                  <span style={{color:'#e8c96a',fontSize:12}}>[{String(i+1).padStart(2,"0")}]</span>
                  <span>{n.isAutoGenerated?"AGENT":"USER"}</span>
                  <span style={{color:'#444'}}>|</span>
                  <span style={{fontWeight:500}}>{n.category}</span>
                  <span style={{color:'#444'}}>|</span>
                  <span style={{fontWeight:500}}>{n.publishedAt}</span>
                </div>
                <h3 style={{fontSize:17,fontWeight:700,color:'#fff',marginBottom:10,lineHeight:1.5}}>{n.title}</h3>
                <p style={{fontSize:14,fontWeight:400,color:'#ccc',lineHeight:1.8}}>{n.summary}</p>
                <p style={{fontFamily:"'JetBrains Mono',monospace",fontSize:10,fontWeight:600,color:'#aaa',marginTop:14,letterSpacing:'0.05em'}}>{n.source}</p>
              </a>
            ))}
          </div>
        )}
      </div>
    </div>
  )
}
