"use client"

import { NewsItem } from "@/data/news"
import { getCurrentUser, addXP, XP_RULES } from "@/data/user"
import { Clock, Globe, User } from "lucide-react"

// 去重：同一天同一篇文章不重复给经验
const readToday = new Set<string>()

function formatDate(dateStr: string): string {
  const date = new Date(dateStr)
  const now = new Date()
  const diffMs = now.getTime() - date.getTime()
  const diffDays = Math.floor(diffMs / (1000 * 60 * 60 * 24))
  if (diffDays === 0) return "今天"
  if (diffDays === 1) return "昨天"
  if (diffDays < 7) return `${diffDays} 天前`
  return dateStr
}

export function NewsCard({ item }: { item: NewsItem }) {
  const handleClick = async () => {
    const user = await getCurrentUser()
    if (!user) return
    const key = `${user.email || user.name}-${item.id}-${new Date().toISOString().slice(0, 10)}`
    if (readToday.has(key)) return
    readToday.add(key)
    addXP(XP_RULES.read_article)
  }

  return (
    <a
      href={item.url}
      target="_blank"
      rel="noopener noreferrer"
      className="card block p-4 no-underline group"
      onClick={handleClick}
    >
      <div className="flex items-center gap-1.5 mb-2 flex-wrap">
        <span
          className={`tag ${
            item.category === "产品发布" ? "tag-blue" :
            item.category === "教程资源" ? "tag-green" :
            item.category === "行业动态" ? "tag-gold" :
            item.category === "政策监管" ? "tag-red" : "tag-gray"
          }`}
        >
          {item.category}
        </span>
        <span className="flex items-center gap-1 text-[10px] text-gray-400">
          {item.isAutoGenerated ? <Globe size={10} /> : <User size={10} />}
          {item.isAutoGenerated ? "Agent" : "用户"}
        </span>
        <span className="flex items-center gap-1 text-[10px] text-gray-400 ml-auto">
          <Clock size={10} /> {formatDate(item.publishedAt)}
        </span>
      </div>

      <h3 className="text-[14px] font-semibold text-gray-900 mb-1.5 leading-snug group-hover:text-primary-600 transition-colors">
        {item.title}
      </h3>

      <p className="text-xs text-gray-500 leading-relaxed line-clamp-2 mb-2">
        {item.summary}
      </p>

      <span className="text-[10px] text-gray-400">{item.source}</span>
    </a>
  )
}
