// 小白AI · AI资讯全自动抓取 v3
// 安装: npm install node-fetch cheerio
// 定时: crontab -e → 0 8,14,20 * * * cd /var/www/xiaobaiai && node scripts/fetch-news.js

const fetch = require("node-fetch")
const cheerio = require("cheerio")
const fs = require("fs")
const path = require("path")

// 国内可访问源 + 国际通用源
const sources = [
  // 国内直连
  { name:"机器之心", url:"https://www.jiqizhixin.com", sel:"h2 a", imp:7, cat:"行业动态" },
  { name:"量子位", url:"https://www.qbitai.com", sel:"h2 a", imp:6, cat:"行业动态" },
  { name:"36氪", url:"https://36kr.com/information/AI", sel:".article-item-title", imp:6, cat:"行业动态" },
  { name:"CSDN AI", url:"https://www.csdn.net/nav/ai", sel:".headline a", imp:5, cat:"教程资源" },
  { name:"Dify Blog", url:"https://dify.ai/blog", sel:"h2 a", imp:6, cat:"教程资源" },
  { name:"WaytoAGI", url:"https://waytoagi.com", sel:"h2 a", imp:5, cat:"教程资源" },
  { name:"GitHub Trending", url:"https://github.com/trending?since=daily", sel:"h2 a", imp:5, cat:"开源项目" },
  { name:"HuggingFace", url:"https://huggingface.co/papers", sel:"h2 a", imp:7, cat:"开源项目" },
  { name:"Coze Blog", url:"https://www.coze.cn/blog", sel:"h2 a", imp:5, cat:"教程资源" },
  { name:"InfoQ AI", url:"https://www.infoq.cn/topic/AI", sel:"h2 a", imp:5, cat:"行业动态" },
]

async function fetchPage(url) {
  try {
    const res = await fetch(url, { headers:{"User-Agent":"Mozilla/5.0 (compatible; XiaobaAI/1.0)"}, timeout:10000 })
    return await res.text()
  } catch(e) { return "" }
}

async function main() {
  console.log(`🔄 小白AI · 全自动资讯抓取 ${new Date().toLocaleString()}`)
  const allNews = []

  for (const src of sources) {
    try {
      const html = await fetchPage(src.url)
      if (!html) { console.log(`  ❌ ${src.name} 无响应`); continue }
      const $ = cheerio.load(html)
      let count = 0
      $(src.sel).each((i, el) => {
        if (count >= 3) return // 每个源最多3条
        const title = $(el).text().trim()
        let link = $(el).attr("href") || ""
        if (!link.startsWith("http")) link = new URL(link, src.url).href
        if (title && title.length > 10 && !allNews.find(n=>n.title===title)) {
          allNews.push({
            id:`auto-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,
            title, summary: title, content:title,
            url:link, source:src.name, category:src.cat,
            publishedAt:new Date().toISOString().slice(0,10),
            importance:src.imp, isAutoGenerated:true, image:""
          })
          count++
        }
      })
      console.log(`  ✅ ${src.name} +${count}`)
    } catch(e) { console.log(`  ⚠️ ${src.name} ${e.message}`)}
    await new Promise(r=>setTimeout(r,1500))
  }

  // 去重 + 排序
  const unique = allNews.filter((n,i)=>allNews.findIndex(x=>x.title===n.title)===i)
    .sort((a,b)=>b.importance-a.importance).slice(0,30)

  const outPath = path.join(__dirname,"..","fetched-news.json")
  fs.writeFileSync(outPath, JSON.stringify(unique,null,2))
  console.log(`✅ 抓到 ${unique.length} 条 → ${outPath}`)

  // 合并到 news.ts (追加模式)
  const newsPath = path.join(__dirname,"..","src","data","news.ts")
  let newsFile = fs.readFileSync(newsPath,"utf8")
  const newItems = unique.map(n=>`  {id:"${n.id}",title:"${n.title.replace(/"/g,'\\"')}",summary:"${n.summary.replace(/"/g,'\\"').slice(0,200)}",content:"${n.content.replace(/"/g,'\\"').slice(0,1000)}",url:"${n.url}",source:"${n.source}",category:"${n.cat}",publishedAt:"${n.publishedAt}",importance:${n.imp},isAutoGenerated:true},\n`).join("")
  newsFile = newsFile.replace(/\]$/m, newItems + "]")
  fs.writeFileSync(newsPath, newsFile)
  console.log("📰 已合并到 news.ts")
}

main()
