// 小白AI · AI资讯全自动抓取 v4（零依赖·原生https）
const https = require("https")
const http = require("http")
const fs = require("fs")
const path = require("path")

// 国内可访问源
const sources = [
  { name:"机器之心", host:"www.jiqizhixin.com", path:"/", imp:7, cat:"行业动态" },
  { name:"量子位", host:"www.qbitai.com", path:"/", imp:6, cat:"行业动态" },
  { name:"CSDN AI", host:"www.csdn.net", path:"/nav/ai", imp:5, cat:"教程资源" },
  { name:"Dify Blog", host:"dify.ai", path:"/blog", imp:6, cat:"教程资源" },
  { name:"GitHub", host:"github.com", path:"/trending?since=daily", imp:5, cat:"开源项目" },
  { name:"InfoQ AI", host:"www.infoq.cn", path:"/topic/AI", imp:5, cat:"行业动态" },
  { name:"知乎AI", host:"www.zhihu.com", path:"/topic/19550901/hot", imp:5, cat:"行业动态" },
  { name:"HuggingFace", host:"huggingface.co", path:"/papers", imp:7, cat:"开源项目" },
]

function getHTML(host, path) {
  return new Promise((resolve) => {
    const mod = path.includes("443") ? https : https
    const opts = { hostname:host, path, method:"GET", headers:{"User-Agent":"Mozilla/5.0","Accept":"text/html"}, timeout:8000 }
    const req = mod.get(opts, res => {
      let data = ""; res.on("data", c => data += c)
      res.on("end", () => resolve(data))
    })
    req.on("error", () => resolve(""))
    req.on("timeout", () => { req.destroy(); resolve("") })
  })
}

function extractTitles(html) {
  const titles = []
  // 提取 h2/h3 中的 a 标签文字
  const regex = /<[hH]([23])[^>]*>.*?<a[^>]*href="([^"]*)"[^>]*>(.+?)<\/a>/g
  let m
  while ((m = regex.exec(html)) !== null) {
    const title = m[3].replace(/<[^>]+>/g, "").trim()
    const link = m[2]
    if (title.length > 10 && title.length < 200 && !titles.find(t => t.title === title)) {
      titles.push({ title, link })
      if (titles.length >= 3) break
    }
  }
  return titles
}

async function main() {
  console.log(`🔄 小白AI · 全自动资讯抓取 ${new Date().toLocaleString()}`)
  const allNews = []

  for (const src of sources) {
    try {
      const html = await getHTML(src.host, src.path)
      if (!html || html.length < 100) { console.log(`  ❌ ${src.name} 无响应`); continue }
      const items = extractTitles(html)
      for (const item of items) {
        const link = item.link.startsWith("http") ? item.link : `https://${src.host}${item.link}`
        allNews.push({
          id:`auto-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,
          title:item.title, summary:item.title, content:item.title,
          url:link, source:src.name, category:src.cat,
          publishedAt:new Date().toISOString().slice(0,10),
          importance:src.imp, isAutoGenerated:true, image:""
        })
      }
      console.log(`  ✅ ${src.name} +${items.length}`)
    } catch(e) { console.log(`  ⚠️ ${src.name} ${e.message}`)}
    await new Promise(r => setTimeout(r, 1500))
  }

  if (allNews.length === 0) { console.log("⚠️ 无新资讯"); return }

  const outPath = path.join(__dirname,"..","fetched-news.json")
  fs.writeFileSync(outPath, JSON.stringify(allNews,null,2))
  console.log(`✅ 抓到 ${allNews.length} 条 → ${outPath}`)

  // 不再合并到 news.ts —— 页面从 fetched-news.json 读取
}

main()
