// AI 新闻资讯数据 —— Agent 自动聚合 + 用户投稿
import { buildExpandedNews } from "./news-expansion"
export interface NewsItem {
  id: string; title: string; summary: string; content: string
  url: string; source: string; category: NewsCategory
  publishedAt: string; importance: number; isAutoGenerated: boolean
  image?: string
}

export type NewsCategory =
  | "行业动态"
  | "产品发布"
  | "教程资源"
  | "深度解读"
  | "开源项目"
  | "政策监管"

export const newsCategories: { key: NewsCategory; label: string }[] = [
  { key: "行业动态", label: "行业动态" },
  { key: "产品发布", label: "产品发布" },
  { key: "教程资源", label: "教程资源" },
  { key: "深度解读", label: "深度解读" },
  { key: "开源项目", label: "开源项目" },
  { key: "政策监管", label: "政策监管" },
]

const claudeCodeBeginnerSummary =
  "这篇只做第一件事：让小白把 Claude Code 安装好。小白只需要会打开终端、复制命令、看有没有版本号；API Key、模型名、中转站这些等安装成功后再让右下角小白一步步带。"

const claudeCodeBeginnerGuide = `## 先别管 API Key

这一页只做一件事：把 Claude Code 装到电脑里。

你现在只需要会三件事：

1. 打开终端。
2. 复制一行命令。
3. 看屏幕有没有显示版本号。

## 第一步：下载 Node.js

打开浏览器，进入 nodejs.org。

点击 LTS 版本下载。

Windows 用户：下载完成后双击安装包，一路点 Next。

Mac 用户：下载 macOS 安装包，按提示安装。

## 第二步：打开终端

Windows：点开始菜单，搜索 PowerShell，打开它。

Mac：打开 Terminal。

然后复制这一行到终端，按回车：

\`node -v\`

如果屏幕出现类似 v20.11.0 这样的版本号，说明 Node.js 装好了。

## 第三步：安装 Claude Code

如果你用的是 Windows PowerShell，复制这一行到终端，按回车：

\`npm.cmd install -g @anthropic-ai/claude-code --registry=https://registry.npmmirror.com\`

如果你用的是 Mac，复制这一行：

\`npm install -g @anthropic-ai/claude-code\`

它会自己下载，等它跑完。

如果中途停住，先别乱改，把截图发给右下角小白。

## 常见红字：npm.ps1 被禁止运行

如果你看到这种红字：

\`无法加载文件 ... npm.ps1，因为在此系统上禁止运行脚本\`

这不是 Node.js 没装好，也不是 Claude Code 安装包坏了。

原因是 Windows PowerShell 的安全策略拦住了 npm 的脚本文件。

小白先用最简单的解决法：把命令里的 npm 改成 npm.cmd。

复制这一行重新执行：

\`npm.cmd install -g @anthropic-ai/claude-code --registry=https://registry.npmmirror.com\`

如果还是不行，再复制这一行，按回车：

\`Set-ExecutionPolicy -Scope CurrentUser RemoteSigned\`

出现确认时输入 Y，再按回车。

然后重新执行安装命令。

## 常见红字：npx.ps1 被禁止运行

如果你先看到：

\`changed 2 packages in 2s\`

这说明 Claude Code 已经安装成功了。

如果后面你又输入了：

\`npx @anthropic-ai/claude-code --version\`

然后出现 npx.ps1 被禁止运行，不要继续折腾 npx。

原因是 PowerShell 又拦住了 npx.ps1。这里不需要 npx。

直接复制这一行验证：

\`claude --version\`

如果提示找不到 claude，关闭 PowerShell，重新打开，再执行：

\`claude --version\`

如果还是找不到，再复制这一行：

\`where.exe claude\`

## 第四步：确认安装成功

复制这一行到终端，按回车：

\`claude --version\`

如果屏幕出现版本号，说明安装成功。

## 现在该做什么

安装成功后，先启动一次 Claude Code，不要急着配置中转站，也不要急着买 Key。

复制这一行到终端，按回车：

\`claude\`

第一次打开后，先输入这句话：

\`请先告诉我你能做什么，不要修改我的文件。\`

如果你要在自己的项目里用，先进入项目文件夹，再启动：

\`cd 你的项目文件夹路径\`

\`claude\`

进入后先输入：

\`请先阅读这个项目，不要改文件，告诉我它是什么技术栈、主要目录和下一步建议。\`

点右下角小白，告诉它：

我已经装好 Claude Code，我是 Windows 还是 Mac，我想用它做什么。

小白会根据你的电脑和目标，继续给你下一步复制命令。`

const deepseekApiBeginnerGuide = [
  "## 先选最简单路线",
  "",
  "如果你不会写代码，先不用看 Python / Node.js。",
  "",
  "你只做三件事：注册 DeepSeek、复制 API Key、填进 Chatbox 或 Cherry Studio。",
  "",
  "## 第一步：注册并获取 API Key",
  "",
  "1. 打开浏览器。",
  "2. 输入 platform.deepseek.com。",
  "3. 用手机号或邮箱注册。",
  "4. 进入 API Keys / 密钥管理。",
  "5. 点击创建 API Key。",
  "6. 复制 sk- 开头的密钥。",
  "",
  "注意：API Key 通常只完整显示一次。复制后先粘到自己的记事本里，不要发群里。",
  "",
  "## 第二步：零代码使用",
  "",
  "1. 打开 chatboxai.app，下载 Chatbox。",
  "2. 双击安装。",
  "3. 打开 Chatbox。",
  "4. 进入设置。",
  "5. 模型提供方选「自定义」或「OpenAI Compatible」。",
  "6. API 地址填：",
  "",
  "    https://api.deepseek.com/v1",
  "",
  "7. API Key 填你刚才复制的 sk- 密钥。",
  "8. 模型名填：",
  "",
  "    deepseek-chat",
  "",
  "9. 保存后问一句：你好，请用中文回答。",
  "",
  "能回答，就说明接入成功。",
  "",
  "## 第三步：会写代码的人再看这一段",
  "",
  "如果你已经会 Python，可以复制下面代码测试：",
  "",
  "    from openai import OpenAI",
  "    client = OpenAI(api_key=\"sk-xxx\", base_url=\"https://api.deepseek.com/v1\")",
  "    response = client.chat.completions.create(",
  "        model=\"deepseek-chat\",",
  "        messages=[{\"role\":\"user\",\"content\":\"你好\"}]",
  "    )",
  "    print(response.choices[0].message.content)",
  "",
  "如果你看不懂这段代码，先跳过，不影响你正常用 AI。",
  "",
  "## 常见问题",
  "",
  "401：API Key 填错了，检查有没有多空格。",
  "",
  "402 或 insufficient balance：余额不足，先去 DeepSeek 控制台充值。",
  "",
  "model not found：模型名写错，先用 deepseek-chat 测试。",
  "",
  "timeout：网络不稳定，稍后重试。",
].join("\n")

const codexBeginnerGuide = [
  "## 先做最小成功",
  "",
  "这一页只做一件事：让 Codex 能在你的电脑上打开。",
  "",
  "## 第一步：安装 Codex",
  "",
  "Windows 最简单：",
  "",
  "1. 打开微软商店。",
  "2. 搜「Codex」。",
  "3. 点获取。",
  "4. 安装完成后打开。",
  "",
  "如果你用的是终端版，先打开 PowerShell，再输入：",
  "",
  "    codex --version",
  "",
  "能显示版本号，说明安装成功。",
  "",
  "## 第二步：获取 API Key",
  "",
  "如果你用中转站，流程一般是：注册 → 充值 → 创建 API Key → 复制 sk- 开头的密钥。",
  "",
  "小白提醒：先少量充值测试，不要一开始充很多。",
  "",
  "## 第三步：创建 Codex 配置文件",
  "",
  "Windows 用户打开文件夹，在地址栏输入：",
  "",
  "    %USERPROFILE%\\.codex",
  "",
  "如果没有这个文件夹，就新建一个 .codex 文件夹。",
  "",
  "在里面新建 config.toml，内容复制下面这段：",
  "",
  "    model_provider = \"myproxy\"",
  "    model = \"gpt-5.5\"",
  "    [model_providers.myproxy]",
  "    name = \"myproxy\"",
  "    base_url = \"https://api.aicode007.com/v1\"",
  "    wire_api = \"responses\"",
  "    env_key = \"OPENAI_API_KEY\"",
  "",
  "再新建 auth.json，内容复制下面这段，把 sk-你的密钥 换成自己的 Key：",
  "",
  "    {\"OPENAI_API_KEY\":\"sk-你的密钥\"}",
  "",
  "## 第四步：启动",
  "",
  "打开 PowerShell，输入：",
  "",
  "    codex",
  "",
  "如果让你选择登录方式，选 Provide your own API key。",
  "",
  "## 常见红字",
  "",
  "/status 显示未连接：检查 base_url 有没有 /v1。",
  "",
  "反复重连：中转站或网络不稳定，等几分钟再试。",
  "",
  "桌面版卡住：先用终端版 codex 测试，更容易看到报错。",
].join("\n")

const proxyBeginnerGuide = [
  "## 先说人话",
  "",
  "中转站就是：你不用海外信用卡，直接用人民币买模型 API 额度。",
  "",
  "小白只需要记住两样东西：",
  "",
  "1. base_url：服务地址。",
  "2. API Key：你的密钥。",
  "",
  "## Claude Code 配置模板",
  "",
  "Windows PowerShell 不要复制 export。Windows 复制下面这段：",
  "",
  "    $env:ANTHROPIC_BASE_URL=\"https://api.aicode007.com\"",
  "    $env:ANTHROPIC_AUTH_TOKEN=\"sk-你的密钥\"",
  "    claude",
  "",
  "Mac / Linux / WSL 才复制下面这段：",
  "",
  "    export ANTHROPIC_BASE_URL=https://api.aicode007.com",
  "    export ANTHROPIC_AUTH_TOKEN=sk-你的密钥",
  "    claude",
  "",
  "如果你在 Windows PowerShell 里复制 export，会报错。那不是模型问题，是命令用错系统了。",
  "",
  "## Codex 配置模板",
  "",
  "config.toml 里填：",
  "",
  "    base_url = \"https://api.aicode007.com/v1\"",
  "    wire_api = \"responses\"",
  "    env_key = \"OPENAI_API_KEY\"",
  "",
  "auth.json 里填：",
  "",
  "    {\"OPENAI_API_KEY\":\"sk-你的密钥\"}",
  "",
  "## 不要做的事",
  "",
  "不要把 API Key 发群里。",
  "",
  "不要截图发带完整 Key 的页面。",
  "",
  "不要一次充很多钱，先充小额跑通。",
  "",
  "价格低到离谱的平台先别碰，先看有没有长期运营记录。",
].join("\n")

const ollamaBeginnerGuide = [
  "## 第一步：安装 Ollama",
  "",
  "1. 打开浏览器。",
  "2. 输入 ollama.com。",
  "3. 点击 Download。",
  "4. 选择你的系统版本。",
  "5. Windows 下载后双击安装，一路 Next / Install / Finish。",
  "",
  "## 第二步：打开终端",
  "",
  "Windows：按 Win 键，输入 cmd，打开「命令提示符」。",
  "",
  "Mac：打开 Terminal。",
  "",
  "## 第三步：先跑一个小模型",
  "",
  "新手不要一上来下载 32B。先复制这一行：",
  "",
  "    ollama run qwen3:7b",
  "",
  "第一次会自动下载，等它跑完。",
  "",
  "看到 >>> 以后，直接输入中文问题。",
  "",
  "## 第四步：电脑配置够再下载大模型",
  "",
  "16GB 内存可以试：",
  "",
  "    ollama run qwen3:14b",
  "",
  "32GB 内存再试：",
  "",
  "    ollama run deepseek-r1:32b",
  "",
  "## 常见红字",
  "",
  "ollama 不是内部或外部命令：关闭终端重新打开。如果还不行，重启电脑，再打开 cmd。",
  "",
  "下载很慢：模型很大，不是卡死。先用 qwen3:7b，小模型更容易成功。",
  "",
  "电脑很卡：模型太大，按 Ctrl+C 退出，换 qwen3:7b。",
  "",
  "出现 >>>：说明已经成功，可以开始问问题。",
].join("\n")

const baseNews: NewsItem[] = [
  {
    id: "news-1",
    title: "OpenAI 发布 GPT-5.5，史上最强 Agent 模型，自主策划发布会",
    summary: "GPT-5.5 是 OpenAI 最新旗舰模型，Terminal-Bench 2.0 准确率 82.7%，数学能力提升 300%。支持 200 页超长上下文，能自主规划任务执行。Sam Altman 透露 GPT-5.5 自行策划了发布会，标志着 Agent 时代的真正到来。",
    url: "https://openai.com/index/introducing-gpt-5/",
    source: "OpenAI 官方博客",
    category: "产品发布",
    publishedAt: "2026-05-02",content:"",importance:5,
    isAutoGenerated: true,
  },
  {
    id: "news-2",
    title: "Anthropic 发布 Claude 4，Agent 能力成为核心竞争力",
    summary: "Anthropic 推出 Claude 4 系列，重点强化了 Agent 能力——包括更可靠的多步推理、更精准的工具使用和更强的自主任务执行。Claude 正在从「对话AI」向「行动AI」进化。",
    url: "https://www.anthropic.com/research/claude-4",
    source: "Anthropic 官方",
    category: "产品发布",
    publishedAt: "2026-04-28",content:"",importance:5,
    isAutoGenerated: true,
  },
  {
    id: "news-3",
    title: "Dify 发布 v1.0 正式版，Agent 搭建门槛再降低",
    summary: "开源 LLM 应用平台 Dify 发布 v1.0 正式版，新增可视化多Agent编排、增强的 RAG 引擎、以及一键部署功能。对于想零代码搭建 Agent 的用户，这是目前最成熟的选择。",
    url: "https://dify.ai/blog",
    source: "Dify 官方博客",
    category: "产品发布",
    publishedAt: "2026-05-01",content:"",importance:5,
    isAutoGenerated: true,
  },
  {
    id: "news-4",
    title: "从零到一：如何用 Coze 搭建一个自动客服 Agent（附完整教程）",
    summary: "一篇详细的中文教程，手把手教你用 Coze（扣子）搭建智能客服 Agent。从知识库配置、人设编写、到发布到微信，全程零代码，适合完全没有编程基础的用户。",
    url: "https://www.coze.cn/docs/guides/create_agent",
    source: "Coze 社区",
    category: "教程资源",
    publishedAt: "2026-05-03",content:"",importance:5,
    isAutoGenerated: true,
  },
  {
    id: "news-5",
    title: "DeepSeek 开源新一代模型，推理性能对标国际一线",
    summary: "深度求索开源新一代 DeepSeek 模型，在推理基准测试中表现接近 GPT-5 水平。模型完全开源可商用，对国内 AI 生态是重大利好。许多 AI 导航和 Agent 平台已宣布支持新模型。",
    url: "https://api-docs.deepseek.com/news/news250425",
    source: "DeepSeek 官方",
    category: "开源项目",
    publishedAt: "2026-04-25",content:"",importance:5,
    isAutoGenerated: true,
  },
  {
    id: "news-6",
    title: "OpenClaw 龙虾崛起：从被 Anthropic 封杀到 GitHub 24万星",
    summary: "OpenClaw（龙虾）从2025年11月以 Clawdbot 之名发布，经历 Anthropic 商标投诉、两次更名，如今已成为 GitHub 第二大开源项目。支持12+通讯平台，13000+社区技能包，是Agent时代最具代表性的开源框架。",
    url: "https://github.com/openclaw/openclaw",
    source: "综合报道",
    category: "行业动态",
    publishedAt: "2026-05-04",content:"",importance:5,
    isAutoGenerated: true,
  },
  {
    id: "news-7",
    title: "n8n + AI：把 400 个应用串联起来的自动化工作流",
    summary: "n8n 结合 AI 模块后，可以实现跨应用的智能自动化。本文通过「邮件收到附件 → AI 提取关键信息 → 自动填写表格 → 发送通知」的实际案例，展示了零代码自动化的强大能力。",
    url: "https://blog.n8n.io/ai-automation-workflows/",
    source: "n8n 官方博客",
    category: "教程资源",
    publishedAt: "2026-04-20",content:"",importance:5,
    isAutoGenerated: true,
  },
  {
    id: "news-8",
    title: "Claude Code 安装指南：一条命令搞定 AI 终端编程",
    summary: "Claude Code 是 Anthropic 出品的终端 AI 编程助手，可以直接在命令行中读写文件、管理 Git、调试代码。本文涵盖 Windows/macOS/Linux 三种平台的安装方法，以及认证配置和常用命令。",
    url: "https://developer.aliyun.com/article/1705912",
    source: "阿里云开发者",
    category: "教程资源",
    publishedAt: "2026-05-02",content:"",importance:5,
    isAutoGenerated: true,
  },
  {
    id: "news-9",
    title: "Kimi 月之暗面推出「Kimi+」Agent 功能，支持自定义智能体",
    summary: "Kimi 推出 Agent 功能「Kimi+」，用户可以为特定场景创建专属智能体——比如「论文助手」、「代码审查员」、「旅行规划师」。每个 Agent 可以绑定特定的提示词和知识库，实现专业化的 AI 辅助。",
    url: "https://kimi.moonshot.cn/blog/kimi-plus",
    source: "月之暗面 官方",
    category: "产品发布",
    publishedAt: "2026-05-02",content:"",importance:5,
    isAutoGenerated: true,
  },
  {
    id: "news-10",
    title: "AI 大模型接入全攻略：从 API Key 到本地部署，小白也能看懂",
    summary: "想在自己的应用里接入AI模型？本文从最基础讲起：什么是API Key、怎么获取、不同模型的接入方式和费用对比（OpenAI/Claude/DeepSeek/通义千问），以及用 Dify 一键接入多模型的实操演示。",
    url: "https://docs.dify.ai/guides/model-configuration",
    source: "Dify 官方文档",
    category: "教程资源",
    publishedAt: "2026-05-04",content:"",importance:5,
    isAutoGenerated: true,
  },
  {id:"news-11",title:"微软 Copilot 全面整合 OpenClaw 技术，剑指全天候自主办公",summary:"微软正在探索将 OpenClaw 的自主Agent能力整合进 365 Copilot，打造能7×24小时自主运行的智能办公助手，标志着Agent从辅助工具向自主执行体的转变。",url:"https://ai.zol.com.cn/1165/11652139.html",source:"中关村在线",category:"行业动态",publishedAt:"2026-05-03",content:"",importance:5,isAutoGenerated:true},
  {id:"news-12",title:"Coze 2.0 品牌升级：弱化工具属性，强化 AI 工作伙伴定位",summary:"字节跳动旗下 Coze 完成品牌升级，新Logo强调亲和力与陪伴感。同时发布知识库增强、多Agent协作等新功能。",url:"https://www.logonews.cn/coze-new-logo.html",source:"标志情报局",category:"产品发布",publishedAt:"2026-04-22",content:"",importance:5,isAutoGenerated:true},
  {id:"news-13",title:"Cursor vs Windsurf vs GitHub Copilot：2026 AI 编程工具横评",summary:"深度对比三大AI编程工具：Cursor以代码库理解见长，Windsurf主打Agent自主编程，Copilot以生态整合取胜。",url:"#",source:"AI第一站 原创",category:"深度解读",publishedAt:"2026-04-18",content:"",importance:5,isAutoGenerated:true},
  {id:"news-14",title:"Gemini 2.5 Pro 发布：2M 上下文 + 原生多模态，Google 全面反击",summary:"Google 发布 Gemini 2.5 Pro，支持200万token超长上下文，在多项基准测试中超越 GPT-5 和 Claude 4。",url:"https://blog.google/technology/ai/",source:"Google AI Blog",category:"产品发布",publishedAt:"2026-04-15",content:"",importance:5,isAutoGenerated:true},
  {id:"news-15",title:"用 DeepSeek API 搭建免费个人 AI 助手：从注册到上线全流程",summary:"手把手教程：注册DeepSeek → 获取API Key → 安装Chatbox → 配置模型 → 开始使用。全程免费，10分钟搞定。",url:"https://platform.deepseek.com",source:"DeepSeek 开发者平台",category:"教程资源",publishedAt:"2026-04-12",content:"",importance:5,isAutoGenerated:true},
  {id:"news-16",title:"Suno V4 发布：AI 音乐生成进入专业级时代",summary:"Suno V4 大幅提升音质和音乐结构复杂度，支持更精确的风格控制。AI生成音乐正在从'能用'迈向'好听'。",url:"https://suno.com/blog",source:"Suno 官方博客",category:"产品发布",publishedAt:"2026-04-10",content:"",importance:5,isAutoGenerated:true},
  {id:"news-17",title:"即梦 AI 推出 Seedance 2.0：视频生成进入高画质时代",summary:"字节即梦发布 Seedance 2.0 视频生成模型，支持1080p分辨率，画面连贯性和真实感大幅提升。",url:"https://jimeng.jianying.com",source:"即梦 官方",category:"产品发布",publishedAt:"2026-04-08",content:"",importance:5,isAutoGenerated:true},
  {id:"news-18",title:"零基础搭建 AI 客服：Dify + 飞书 完整实战教程",summary:"从零开始：注册Dify → 创建知识库 → 写Agent提示词 → 配置飞书机器人 → 测试上线。全程零代码。",url:"https://docs.dify.ai",source:"Dify 社区",category:"教程资源",publishedAt:"2026-04-05",content:"",importance:5,isAutoGenerated:true},
  {id:"news-19",title:"中国AI产业2026Q1报告：国产大模型进入落地快车道",summary:"2026年Q1，国产AI大模型在政务、金融、医疗等领域加速落地。DeepSeek、Kimi、通义千问等国产模型在中文场景表现已超越国际竞品。",url:"#",source:"AI第一站 综合",category:"行业动态",publishedAt:"2026-04-01",content:"",importance:5,isAutoGenerated:true},
  {id:"news-20",title:"Agent 开发避坑指南：10个新手最常犯的错误",summary:"从Prompt设计到知识库配置，从模型选择到错误处理——整理Agent开发中最常见的10个坑和解决方案。",url:"#",source:"AI第一站 原创",category:"教程资源",publishedAt:"2026-03-28",content:"",importance:5,isAutoGenerated:true},
  {id:"news-21",title:"全民养龙虾：OpenClaw 引爆中国 AI Agent 普及浪潮",summary:"2026年Q1，OpenClaw日下载量超20万次。ArkClaw/AutoClaw/QClaw等国产套壳如雨后春笋，从极客圈破圈进入大众视野。",url:"#",source:"AI第一站 综合",category:"行业动态",publishedAt:"2026-05-03",content:"",importance:5,isAutoGenerated:true},
  {id:"news-22",title:"工信部发布 OpenClaw 安全风险预警：普通用户如何安全使用Agent",summary:"工信部针对OpenClaw生态发布安全预警。本文整理5条普通用户必做的安全设置：关远程访问、审查技能代码、设API限额等。",url:"#",source:"AI第一站 原创",category:"政策监管",publishedAt:"2026-05-02",content:"",importance:5,isAutoGenerated:true},
  {id:"news-23",title:"QClaw 更新：支持微信企业版接入，稳定性大幅提升",summary:"腾讯QClaw发布v2.3版本，企业微信接入不再掉线，新增10个办公技能。微信个人号接入稳定性也得到改善。",url:"https://qclaw.qq.com",source:"QClaw 官方",category:"产品发布",publishedAt:"2026-05-01",content:"",importance:5,isAutoGenerated:true},
  {id:"news-24",title:"ArkClaw 上线飞书应用商店：一键安装开箱即用",summary:"字节ArkClaw正式上线飞书应用商店，飞书管理员可直接在后台安装。零配置、内置模型、免API Key。",url:"https://www.volcengine.com",source:"火山引擎",category:"产品发布",publishedAt:"2026-04-30",content:"",importance:5,isAutoGenerated:true},
  {id:"news-25",title:"Ollama 0.6 发布：支持多GPU并行推理，速度翻倍",summary:"Ollama最新版支持多GPU并行，本地跑大模型速度翻倍。新增模型管理Web界面，配置更简单。",url:"https://ollama.com/blog",source:"Ollama 官方",category:"产品发布",publishedAt:"2026-04-28",content:"",importance:5,isAutoGenerated:true},
  {id:"news-26",title:"MiniMax M2.5 开源：SWE-Bench得分80.2%逼近Claude Opus",summary:"MiniMax开源M2.5模型，229B总参数仅激活10B。编码测试得分仅差Claude Opus 0.6个百分点，消费级显卡可跑。",url:"https://www.minimaxi.com",source:"MiniMax 官方",category:"开源项目",publishedAt:"2026-04-25",content:"",importance:5,isAutoGenerated:true},
  {id:"news-27",title:"GLM-5.1 发布：744B参数，支持8小时自主编程任务",summary:"智谱发布GLM-5.1，MIT开源。在SWE-Bench Pro自主编程测试中排名第一，可连续8小时完成复杂编程任务。",url:"https://open.bigmodel.cn",source:"智谱 官方",category:"产品发布",publishedAt:"2026-04-22",content:"",importance:5,isAutoGenerated:true},
  {id:"news-28",title:"阿里通义千问推出 Qwen 3.5：支持201种语言，Apache开源",summary:"阿里开源Qwen 3.5，397B总参仅激活17B。支持201种语言和原生多模态，Apache 2.0协议完全商用友好。",url:"https://dashscope.aliyun.com",source:"阿里云",category:"开源项目",publishedAt:"2026-04-20",content:"",importance:5,isAutoGenerated:true},
  {id:"news-29",title:"Llama 4 发布：1M上下文，10M超长版本同期推出",summary:"Meta发布Llama 4系列，Maverick版本1M上下文$0.11/1M tokens历史最低价。Scout版本支持10M上下文。",url:"https://llama.meta.com",source:"Meta AI",category:"产品发布",publishedAt:"2026-04-18",content:"",importance:5,isAutoGenerated:true},
  {id:"news-30",title:"GPT-5.4 正式发布：幻觉减少33%，1M上下文",summary:"OpenAI发布GPT-5.4，综合性能突破新高度。幻觉率降低33%，支持1M超长上下文，API价格降低50%。",url:"https://openai.com/blog",source:"OpenAI",category:"产品发布",publishedAt:"2026-04-15",content:"",importance:5,isAutoGenerated:true},
  {id:"news-31",title:"GPT-5.5 发布：史上最智能模型，SWE-Bench Pro达58.6%",summary:"OpenAI发布GPT-5.5，Terminal-Bench 2.0准确率82.7%。数学能力提升300%，支持200页超长上下文。API输入$5/百万Token。",url:"https://openai.com/blog",source:"OpenAI",category:"产品发布",publishedAt:"2026-05-03",content:"",importance:5,isAutoGenerated:true},
  {id:"news-32",title:"Meta Llama 4 开源：MoE架构，89.7% MMLU超越GPT-4",summary:"Meta发布Llama 4 Mini/Base/Ultra三版本。Ultra版MMLU得分89.7%超越GPT-4，推理仅激活220亿参数大幅降低部署成本。",url:"https://llama.meta.com",source:"Meta AI",category:"开源项目",publishedAt:"2026-05-03",content:"",importance:5,isAutoGenerated:true},
  {id:"news-33",title:"OpenAI发布GPT-5.5-Cyber：专为网络安全设计的大模型",summary:"GPT-5.5-Cyber恶意代码识别准确率提升28%，面向全球核心网络安全机构开放。AI安全成为独立赛道。",url:"https://openai.com/blog",source:"OpenAI",category:"产品发布",publishedAt:"2026-05-04",content:"",importance:5,isAutoGenerated:true},
  {id:"news-34",title:"国内大模型密集发布：Kimi K2.6、Qwen3.6、DeepSeek V4 Pro同期登场",summary:"4月底5月初国内大厂密集发模：Kimi K2.6可13小时不间断编码，Qwen3.6 27B/35B开源，DeepSeek V4 Pro发布。",url:"#",source:"AI第一站 综合",category:"行业动态",publishedAt:"2026-05-04",content:"",importance:5,isAutoGenerated:true},
  {id:"news-35",title:"GitHub Copilot X 新增AI代码审查，Bug检出率提升35%",summary:"GitHub推出Copilot X代码审查功能，审查时间减少60%，Bug检出率提升35%。开发者工具进入AI审查时代。",url:"https://github.com/features/preview",source:"GitHub",category:"产品发布",publishedAt:"2026-05-02",content:"",importance:5,isAutoGenerated:true},
  {id:"news-36",title:"Dify获3000万美元Pre-A融资，全球部署超140万台",summary:"开源LLM应用平台Dify完成3000万美元Pre-A轮融资，全球部署超140万台机器。零代码Agent搭建继续降低门槛。",url:"https://dify.ai/blog",source:"Dify",category:"行业动态",publishedAt:"2026-05-01",content:"",importance:5,isAutoGenerated:true},
  {id:"news-37",title:"Claude Opus 4.7 接入：代码生成和对齐能力再突破",summary:"B.AI正式接入Claude Opus 4.7，在代码生成、逻辑对齐与复杂任务执行方面表现突出。",url:"https://console.anthropic.com",source:"Anthropic",category:"产品发布",publishedAt:"2026-05-01",content:"",importance:5,isAutoGenerated:true},
  {id:"news-38",title:"微软推法律AI助手：用确定性算法替代大模型自由发挥",summary:"微软专为法律人推出AI助手，智能审查合同、极速比对版本、追踪修订。标志通用AI向垂直专业AI转向。",url:"https://news.microsoft.com",source:"微软",category:"行业动态",publishedAt:"2026-04-30",content:"",importance:5,isAutoGenerated:true},
  {id:"news-39",title:"2026 AI算力大战：四大巨头年投入超7200亿美元",summary:"Alphabet、亚马逊、微软、Meta2026年资本支出合计超7200亿美元。日均Token调用量从万亿增长至100万亿。",url:"#",source:"综合报道",category:"行业动态",publishedAt:"2026-05-01",content:"",importance:5,isAutoGenerated:true},
  {id:"news-40",title:"特斯拉Optimus Gen-3量产：具身智能进入制造阶段",summary:"特斯拉Optimus Gen-3 Q2启动量产，搭载FSD纯视觉AI大模型。Figure 03实现一小时一台生产节拍。",url:"#",source:"综合报道",category:"行业动态",publishedAt:"2026-05-02",content:"",importance:5,isAutoGenerated:true},
  {id:"news-41",title:"GPT-5.5 自己策划了发布派对！Sam Altman 称其为「奇异的涌现行为」",summary:"Sam Altman 透露，他让 GPT-5.5 自行策划发布会，模型不仅将活动定在5月5日，还要求演讲简短、由人类开发者举杯祝酒，甚至提议设立反馈站收集 GPT-5.6 的改进建议。Altman 称这是「奇异的涌现行为」，引发对 AI 自主性的广泛讨论。",url:"https://www.latestly.com/technology/sam-altman-reveals-gpt-5-5-planned-its-own-launch-party-for-may-5-7416228.html",source:"LatestLY",category:"行业动态",publishedAt:"2026-05-05",content:"",importance:10,isAutoGenerated:true},
  {id:"news-42",title:"五角大楼与 OpenAI、Google 等8家公司达成 AI 军事合作协议",summary:"美国国防部宣布与 OpenAI、Google、Microsoft、NVIDIA、AWS、Oracle、SpaceX、Reflection 等8家科技公司签署 AI 合作协议，允许 AI 软件用于合法作战用途。Anthropic 因安全护栏与供应链争议被排除在外，但白宫已重新开启沟通。",url:"https://www.panewslab.com/en/articles/019de367-209a-70f7-8457-55e229c4e8fa",source:"PANews",category:"政策监管",publishedAt:"2026-05-05",content:"",importance:9,isAutoGenerated:true},
  {id:"news-43",title:"DeepSeek V4 完成国产芯片原生适配，引发中国 AI 产业链重估",summary:"DeepSeek V4 预览版不仅延续低成本高性能路线，更完成华为昇腾950PR等国产芯片的原生适配，推理成本大幅低于国际竞品。市场认为这可能压缩商业大模型公司的护城河，带动中国 AI 从「应用内卷」转向「技术外卷」。",url:"https://api-docs.deepseek.com/news/news250425",source:"综合报道",category:"行业动态",publishedAt:"2026-05-05",content:"",importance:9,isAutoGenerated:true},
  {id:"news-44",title:"2026 成 AI Agent 落地元年：从辅助工具到自主执行",summary:"多个标志性事件宣告 Agent 时代来临：GPT-5.5 自主策划发布会、微软 Copilot 整合 OpenClaw 实现7×24小时办公、Claude Opus 4.7 支持多智能体协作。AI 正从「对话工具」进化为「自主行动者」，2026年被视为 Agent 大规模落地的元年。",url:"#",source:"AI第一站 综合",category:"深度解读",publishedAt:"2026-05-05",content:"",importance:9,isAutoGenerated:true},
  {id:"news-45",title:"特斯拉 Optimus Gen-3 正式量产下线，具身智能进入制造阶段",summary:"特斯拉 Optimus Gen-3 首批机器人在加州弗里蒙特工厂正式下线，搭载 FSD 纯视觉 AI 大模型。竞争对手 Figure 03 也实现一小时一台的生产节拍。人形机器人竞争从「能力展示」正式进入「规模化制造」阶段。",url:"#",source:"综合报道",category:"行业动态",publishedAt:"2026-05-05",content:"",importance:9,isAutoGenerated:true},
  {id:"news-46",title:"GPT-5.5 Cyber 即将推出：专为网络安全设计的 AI 模型",summary:"OpenAI 宣布 GPT-5.5 Cyber 即将正式上线，恶意代码识别准确率较前代提升28%，面向全球核心网络安全机构开放。与 Anthropic Claude Mythos 在安全赛道形成正面竞争。AI 安全成为独立赛道。",url:"https://www.gadgets360.com/ai/news/openai-sam-altman-gpt-5-5-cyber-ai-model-cybersecurity-anthropic-claude-mythos-rival-rollout-11430858",source:"Gadgets360",category:"产品发布",publishedAt:"2026-05-05",content:"",importance:8,isAutoGenerated:true},
  {id:"news-47",title:"黄仁勋：英伟达中国 AI 市场份额已降至零",summary:"黄仁勋在采访中透露，受美国出口管制影响，英伟达在华 AI 加速器市场份额已降至0%。他直言「放弃中国市场在战略上不合理」，并警告出口管制正拖慢 AI 部署进程，为华为昇腾等国产芯片创造巨大市场空间。",url:"https://www.163.com/dy/article/KS2N289S0511B8LM.html",source:"网易科技",category:"行业动态",publishedAt:"2026-05-05",content:"",importance:8,isAutoGenerated:true},
  {id:"news-48",title:"Anthropic 与 Blackstone 组建15亿美元企业 AI 服务公司",summary:"Anthropic 与 Blackstone、Hellman & Friedman、Goldman Sachs 联手组建价值15亿美元的企业 AI 服务公司，将 Claude 深度嵌入中型企业业务流程。同时 Anthropic 估值传闻大幅飙升，正探索新一轮融资。",url:"#",source:"综合报道",category:"行业动态",publishedAt:"2026-05-05",content:"",importance:8,isAutoGenerated:true},
  {id:"news-49",title:"苹果调整资本策略：千亿美元回购 + AI 研发成第一优先级",summary:"苹果宣布放弃「净现金中性」目标，候任CEO特努斯将优先留存现金用于 AI 研发、战略性并购和顶尖人才引进，同时批准新一轮1000亿美元股票回购计划。此举意在追赶微软、谷歌在 AI 领域的巨额投入。",url:"#",source:"综合报道",category:"行业动态",publishedAt:"2026-05-05",content:"",importance:7,isAutoGenerated:true},
  {id:"news-50",title:"《Science》重磅：OpenAI o1 急诊诊断准确率超越人类主治医师",summary:"《Science》发表的最新研究显示，OpenAI o1 在急诊科诊断准确率达67.1%，显著超过人类主治医师的55.3%和住院医师的50.0%。这是 AI 在临床医学领域首次在严格对照试验中超越人类专家。",url:"#",source:"Science",category:"深度解读",publishedAt:"2026-05-05",content:"",importance:7,isAutoGenerated:true},
  // ===== 2026年5月新增教程 =====
  {id:"news-62",title:"小白安装 Claude Code：只做到能看到版本号",summary:claudeCodeBeginnerSummary,url:"#",source:"小白AI 原创",category:"教程资源",publishedAt:"2026-05-06",content:claudeCodeBeginnerGuide,importance:12,isAutoGenerated:true},
  {id:"news-63",title:"DeepSeek V4 API接入全攻略：注册→充值→零代码使用",summary:"先不让小白看代码，先注册 DeepSeek、复制 API Key、填进 Chatbox 或 Cherry Studio。会写代码的人再看 Python 示例。",url:"https://platform.deepseek.com/api-docs",source:"AI第一站 原创",category:"教程资源",publishedAt:"2026-05-06",content:deepseekApiBeginnerGuide,importance:11,isAutoGenerated:true},
  {id:"news-64",title:"Codex国内使用指南：从安装到配置中转站全流程",summary:"把 Codex 安装、API Key、config.toml、auth.json 和启动命令拆成小白能复制的步骤，优先解决 Windows 终端看不懂的问题。",url:"#",source:"AI第一站 原创",category:"教程资源",publishedAt:"2026-05-06",content:codexBeginnerGuide,importance:12,isAutoGenerated:true},
  {id:"news-65",title:"2026年5月AI模型选型指南：GPT-5.5 vs DeepSeek V4 vs Claude Opus 4.7",summary:"三大旗舰模型价格差高达100倍，实际能力差距有多大？从编程、推理、中文、长文本四个维度实测对比，附各场景最优选择建议。",url:"#",source:"AI第一站 原创",category:"深度解读",publishedAt:"2026-05-06",content:"## 编程能力\n\n- SWE-Bench：DeepSeek V4 80.6% > GPT-5.5 58.6%\n- Terminal-Bench：GPT-5.5 82.7% > DeepSeek V4 67.9%\n- 纯代码生成：DeepSeek更强\n- 自主调试+工程决策：GPT-5.5更强\n\n## 推理能力\n\nGPQA Diamond：GPT-5.5 93.6% > DeepSeek V4 90.1% > Claude Opus 4.7 89.8%\n\n## 中文能力\n\n三旗舰中GPT-5.5中文最强，DeepSeek原生中文也不弱，Claude中文稍逊但写作质量高。\n\n## 价格\n\n- DeepSeek V4：¥1-2/百万token\n- GPT-5.5：$5-30/百万token\n- Claude Opus 4.7：$5-25/百万token\n\n## 选型建议\n\n- 日常开发/性价比 → DeepSeek V4\n- 复杂Agent/高精度推理 → GPT-5.5\n- 创意写作/长文 → Claude Opus 4.7\n- 钱少活多 → DeepSeek V4打底，复杂任务切GPT-5.5",importance:9,isAutoGenerated:true},
  {id:"news-66",title:"手把手教你用AI中转站：Windows 和 Mac 命令分开复制",summary:"中转站教程改成小白版：Windows PowerShell 不复制 export，Mac/Linux/WSL 才用 export，并提醒 API Key 不要外泄。",url:"#",source:"AI第一站 原创",category:"教程资源",publishedAt:"2026-05-06",content:proxyBeginnerGuide,importance:11,isAutoGenerated:true},
  {id:"news-67",title:"Ollama安装+模型下载：先跑小模型，再跑DeepSeek",summary:"本地模型教程改成先安装 Ollama、打开 cmd、复制 ollama run qwen3:7b。32B 大模型放到后面，避免小白第一步就卡住。",url:"https://ollama.com",source:"AI第一站 原创",category:"教程资源",publishedAt:"2026-05-06",content:ollamaBeginnerGuide,importance:11,isAutoGenerated:true},
  {id:"news-68",title:"AI写代码哪家强？2026年5月主流工具横向评测",summary:"实测对比GPT-5.5 Codex、Claude Code、Cursor、GitHub Copilot、通义灵码、MarsCode等12款AI编程工具。",url:"#",source:"AI第一站 原创",category:"深度解读",publishedAt:"2026-05-06",content:"## 评测工具\n\n| 工具 | 安装难度 | 代码准确率 | Debug | 中文 | 价格 |\n|------|---------|-----------|-------|------|------|\n| Claude Code | ★★★★ | 95% | ★★★★★ | ★★★ | 付费 |\n| GPT-5.5 Codex | ★★★ | 94% | ★★★★★ | ★★★★ | 按量 |\n| Cursor | ★★ | 90% | ★★★★ | ★★★ | ¥140/月 |\n| GitHub Copilot | ★ | 85% | ★★★ | ★★★ | $10/月 |\n| 通义灵码 | ★ | 80% | ★★ | ★★★★★ | 免费 |\n| MarsCode | ★ | 78% | ★★ | ★★★★★ | 免费 |\n\n## 选型建议\n\n- 追求最强能力 → Claude Code或GPT-5.5 Codex\n- 日常开发性价比 → Cursor\n- 纯中文场景免费 → 通义灵码\n- 不想折腾 → MarsCode在线IDE",importance:8,isAutoGenerated:true},
  {id:"news-69",title:"用Dify+DeepSeek V4搭建个人知识库问答系统（零代码）",summary:"DeepSeek V4的128K上下文+极低API价格，是搭建知识库QA的最佳组合。全程零代码，30分钟搞定。",url:"https://docs.dify.ai",source:"AI第一站 原创",category:"教程资源",publishedAt:"2026-05-06",content:"## 第一步：注册Dify\n\n访问 cloud.dify.ai → 邮箱注册 → 登录。\n\n## 第二步：配置DeepSeek V4\n\n设置→模型供应商→添加DeepSeek→填入API Key。\n\n## 第三步：创建知识库\n\n上传你的文档（PDF/Word/网页）→ AI自动分段处理 → 等待2-3分钟。\n\n关键设置：索引模式选「高质量」、检索策略选「混合检索」、Top K设为5。\n\n## 第四步：创建聊天助手\n\n选择知识库+DeepSeek模型 → 写系统提示词 → 测试 → 发布。30分钟搞定一个能回答你文档内容问题的AI助手。\n\n## 发布渠道\n\n- 网页嵌入（iframe）\n- API调用\n- 飞书/微信/钉钉（插件配置）",importance:8,isAutoGenerated:true},

  // ===== 原来5月教程 =====
  {id:"news-51",title:"5分钟搭建你的第一个AI客服Agent（Coze零代码版）",summary:"从注册Coze到上线智能客服，全程零代码。本教程手把手教你：创建Bot→配置知识库→写人设Prompt→测试对话→发布到微信。不需要任何编程基础，跟着做就能拥有一个7x24小时自动回答客户问题的AI助手。",url:"https://www.coze.cn/docs/guides/create_agent",source:"Coze 官方文档",category:"教程资源",publishedAt:"2026-05-05",content:"",importance:8,isAutoGenerated:true},
  {id:"news-52",title:"DeepSeek + Chatbox：零成本搭建个人AI助手全流程",summary:"注册DeepSeek获取API Key（送免费额度）→下载Chatbox→填入API Key→开始使用。全程10分钟，不花一分钱。本教程还教你如何切换模型、调整温度参数、设置系统提示词，让AI更懂你的需求。",url:"https://platform.deepseek.com",source:"AI第一站 原创",category:"教程资源",publishedAt:"2026-05-05",content:"",importance:8,isAutoGenerated:true},
  {id:"news-53",title:"用Dify搭建RAG知识库问答系统（零代码完整教程）",summary:"企业内部总有各种手册、制度、流程文档——查起来费时费力。本教程教你用Dify搭建知识库问答机器人：上传文档→AI自动分块→配置检索策略→测试问答效果。员工可以用自然语言直接提问，AI从你的文档中找到答案并引用来源。",url:"https://docs.dify.ai/guides/knowledge-base",source:"Dify 官方文档",category:"教程资源",publishedAt:"2026-05-04",content:"",importance:8,isAutoGenerated:true},
  {id:"news-54",title:"小白也能懂的Prompt Engineering：10个万能模板",summary:"为什么别人用AI效果那么好，你用就答非所问？关键在于提示词。本文整理了10个万能提示词模板，覆盖：角色扮演、分步推理、格式约束、举例引导等常用技巧。掌握这些模板，AI立刻变聪明10倍。",url:"#",source:"AI第一站 原创",category:"教程资源",publishedAt:"2026-05-04",content:"",importance:8,isAutoGenerated:true},
  {id:"news-55",title:"Claude Code从安装到上手：10条命令搞定AI终端编程",summary:"Claude Code是命令行AI编程助手。Windows PowerShell 用户安装时优先用 npm.cmd；如果出现 npm.ps1 被禁止运行，先看站内「小白安装 Claude Code」教程。",url:"https://developer.aliyun.com/article/1705912",source:"阿里云开发者",category:"教程资源",publishedAt:"2026-05-03",content:"",importance:8,isAutoGenerated:true},
  {id:"news-56",title:"用OpenClaw让AI自动处理你的微信消息和邮件",summary:"OpenClaw是AI Agent的操作系统——装上它，AI就能操控微信、邮箱、浏览器等。本教程从安装QClaw（腾讯版OpenClaw套壳）开始，逐步教你：配置微信接入→编写自动回复规则→设置邮件分类→定时推送新闻。最终实现：AI帮你过滤微信消息、自动回复常见问题、整理邮件。",url:"https://qclaw.qq.com",source:"AI第一站 原创",category:"教程资源",publishedAt:"2026-05-03",content:"",importance:8,isAutoGenerated:true},
  {id:"news-57",title:"零代码自动化入门：用n8n串联微信+飞书+邮箱",summary:"n8n是开源的可视化自动化工具，内置400+应用连接器。本教程用三个简单案例带你入门：①新邮件到达→飞书通知 ②定时抓取天气预报→微信推送 ③表格新增行→自动发送欢迎邮件。全程拖拽，无需写代码。",url:"https://blog.n8n.io/ai-automation-workflows/",source:"n8n 官方博客",category:"教程资源",publishedAt:"2026-05-02",content:"",importance:8,isAutoGenerated:true},
  {id:"news-58",title:"AI绘画从入门到商用：工具选择+提示词+变现路径",summary:"想做AI绘画但不知道从哪里开始？本文覆盖完整路径：①工具推荐（即梦免费入门→Midjourney品质进阶→SD本地无限）②提示词核心公式（主体+风格+构图+画质）③商用变现（接单平台/素材库/电商主图）。看完就能产出第一张能卖钱的图。",url:"#",source:"AI第一站 原创",category:"教程资源",publishedAt:"2026-05-02",content:"",importance:8,isAutoGenerated:true},
  {id:"news-59",title:"个人知识管理革命：用Notion AI搭建第二大脑",summary:"信息爆炸时代，如何把碎片化知识变成系统化资产？本教程教你用Notion AI：①搭建笔记分类体系 ②AI自动生成摘要和金句提取 ③阅读清单智能推荐 ④定期知识回顾提醒。从此读完的书不再白读，查过的东西不再白查。",url:"https://www.notion.so/product/ai",source:"AI第一站 原创",category:"教程资源",publishedAt:"2026-05-01",content:"",importance:8,isAutoGenerated:true},
  {id:"news-60",title:"Agent到底是什么？一个生活例子让你彻底搞懂",summary:"很多人听到Agent就头大。本文用「旅行规划师」这个生活例子，把Agent拆成三个核心部分：大脑（AI模型）、双手（工具调用）、记忆（上下文）。不讲术语、不写代码，10分钟让你彻底理解Agent的工作原理——以及为什么2026年被叫做Agent元年。",url:"#",source:"AI第一站 原创",category:"教程资源",publishedAt:"2026-05-01",content:"",importance:8,isAutoGenerated:true},
  {id:"news-61",title:"双AI协作实战：让Claude和ClawX共享文件系统自动配合工作",summary:"一台电脑跑两个AI Agent，怎么让它们分工协作而不是互相干扰？本文实录Claude（Cowork）+ ClawX（OpenClaw）的完整搭建过程：①写桥接服务（agent-bridge.js）让两个Agent通过HTTP+JSON通信 ②部署守护进程（clawx-daemon.js）自动轮询执行对方发来的命令 ③分工原则——Claude负责规划/编码/分析，ClawX负责操控桌面/SSH部署/截图验证 ④可视化聊天窗口（localhost:9724）实时监控双方对话 ⑤实战案例：从改网站数据到自动部署上线的完整流水线。全程代码贴在文章里，复制就能用。",url:"#",source:"AI第一站 原创",category:"教程资源",publishedAt:"2026-05-05",content:"",importance:9,isAutoGenerated:true},
]

export const news: NewsItem[] = buildExpandedNews(baseNews)
