// AI 新闻资讯数据 —— Agent 自动聚合 + 用户投稿
export interface NewsItem {
  id: string
  title: string
  summary: string
  url: string
  source: string
  category: NewsCategory
  publishedAt: string
  isAutoGenerated: boolean  // true = Agent维护, false = 用户投稿
}

export type NewsCategory =
  | "行业动态"
  | "产品发布"
  | "教程资源"
  | "深度解读"
  | "开源项目"
  | "政策监管"

export const newsCategories: { key: NewsCategory; label: string }[] = [
  { key: "行业动态", label: "行业动态" },
  { key: "产品发布", label: "产品发布" },
  { key: "教程资源", label: "教程资源" },
  { key: "深度解读", label: "深度解读" },
  { key: "开源项目", label: "开源项目" },
  { key: "政策监管", label: "政策监管" },
]

export const news: NewsItem[] = [
  {
    id: "news-1",
    title: "OpenAI 发布 GPT-5 系列模型，推理能力大幅提升",
    summary: "OpenAI 正式发布 GPT-5 系列，在复杂推理、数学和代码生成方面取得显著进步。新模型支持更长的上下文窗口和更精准的工具调用能力，对 Agent 开发者是重大利好。",
    url: "https://openai.com/index/introducing-gpt-5/",
    source: "OpenAI 官方博客",
    category: "产品发布",
    publishedAt: "2026-05-02",
    isAutoGenerated: true,
  },
  {
    id: "news-2",
    title: "Anthropic 发布 Claude 4，Agent 能力成为核心竞争力",
    summary: "Anthropic 推出 Claude 4 系列，重点强化了 Agent 能力——包括更可靠的多步推理、更精准的工具使用和更强的自主任务执行。Claude 正在从「对话AI」向「行动AI」进化。",
    url: "https://www.anthropic.com/research/claude-4",
    source: "Anthropic 官方",
    category: "产品发布",
    publishedAt: "2026-04-28",
    isAutoGenerated: true,
  },
  {
    id: "news-3",
    title: "Dify 发布 v1.0 正式版，Agent 搭建门槛再降低",
    summary: "开源 LLM 应用平台 Dify 发布 v1.0 正式版，新增可视化多Agent编排、增强的 RAG 引擎、以及一键部署功能。对于想零代码搭建 Agent 的用户，这是目前最成熟的选择。",
    url: "https://dify.ai/blog",
    source: "Dify 官方博客",
    category: "产品发布",
    publishedAt: "2026-05-01",
    isAutoGenerated: true,
  },
  {
    id: "news-4",
    title: "从零到一：如何用 Coze 搭建一个自动客服 Agent（附完整教程）",
    summary: "一篇详细的中文教程，手把手教你用 Coze（扣子）搭建智能客服 Agent。从知识库配置、人设编写、到发布到微信，全程零代码，适合完全没有编程基础的用户。",
    url: "https://www.coze.cn/docs/guides/create_agent",
    source: "Coze 社区",
    category: "教程资源",
    publishedAt: "2026-05-03",
    isAutoGenerated: true,
  },
  {
    id: "news-5",
    title: "DeepSeek 开源新一代模型，推理性能对标国际一线",
    summary: "深度求索开源新一代 DeepSeek 模型，在推理基准测试中表现接近 GPT-5 水平。模型完全开源可商用，对国内 AI 生态是重大利好。许多 AI 导航和 Agent 平台已宣布支持新模型。",
    url: "https://api-docs.deepseek.com/news/news250425",
    source: "DeepSeek 官方",
    category: "开源项目",
    publishedAt: "2026-04-25",
    isAutoGenerated: true,
  },
  {
    id: "news-6",
    title: "OpenClaw 龙虾崛起：从被 Anthropic 封杀到 GitHub 24万星",
    summary: "OpenClaw（龙虾）从2025年11月以 Clawdbot 之名发布，经历 Anthropic 商标投诉、两次更名，如今已成为 GitHub 第二大开源项目。支持12+通讯平台，13000+社区技能包，是Agent时代最具代表性的开源框架。",
    url: "https://github.com/openclaw/openclaw",
    source: "综合报道",
    category: "行业动态",
    publishedAt: "2026-05-04",
    isAutoGenerated: true,
  },
  {
    id: "news-7",
    title: "n8n + AI：把 400 个应用串联起来的自动化工作流",
    summary: "n8n 结合 AI 模块后，可以实现跨应用的智能自动化。本文通过「邮件收到附件 → AI 提取关键信息 → 自动填写表格 → 发送通知」的实际案例，展示了零代码自动化的强大能力。",
    url: "https://blog.n8n.io/ai-automation-workflows/",
    source: "n8n 官方博客",
    category: "教程资源",
    publishedAt: "2026-04-20",
    isAutoGenerated: true,
  },
  {
    id: "news-8",
    title: "Claude Code 安装指南：一条命令搞定 AI 终端编程",
    summary: "Claude Code 是 Anthropic 出品的终端 AI 编程助手，可以直接在命令行中读写文件、管理 Git、调试代码。本文涵盖 Windows/macOS/Linux 三种平台的安装方法，以及认证配置和常用命令。",
    url: "https://developer.aliyun.com/article/1705912",
    source: "阿里云开发者",
    category: "教程资源",
    publishedAt: "2026-05-02",
    isAutoGenerated: true,
  },
  {
    id: "news-9",
    title: "Kimi 月之暗面推出「Kimi+」Agent 功能，支持自定义智能体",
    summary: "Kimi 推出 Agent 功能「Kimi+」，用户可以为特定场景创建专属智能体——比如「论文助手」、「代码审查员」、「旅行规划师」。每个 Agent 可以绑定特定的提示词和知识库，实现专业化的 AI 辅助。",
    url: "https://kimi.moonshot.cn/blog/kimi-plus",
    source: "月之暗面 官方",
    category: "产品发布",
    publishedAt: "2026-05-02",
    isAutoGenerated: true,
  },
  {
    id: "news-10",
    title: "AI 大模型接入全攻略：从 API Key 到本地部署，小白也能看懂",
    summary: "想在自己的应用里接入AI模型？本文从最基础讲起：什么是API Key、怎么获取、不同模型的接入方式和费用对比（OpenAI/Claude/DeepSeek/通义千问），以及用 Dify 一键接入多模型的实操演示。",
    url: "https://docs.dify.ai/guides/model-configuration",
    source: "Dify 官方文档",
    category: "教程资源",
    publishedAt: "2026-05-04",
    isAutoGenerated: true,
  },
  {id:"news-11",title:"微软 Copilot 全面整合 OpenClaw 技术，剑指全天候自主办公",summary:"微软正在探索将 OpenClaw 的自主Agent能力整合进 365 Copilot，打造能7×24小时自主运行的智能办公助手，标志着Agent从辅助工具向自主执行体的转变。",url:"https://ai.zol.com.cn/1165/11652139.html",source:"中关村在线",category:"行业动态",publishedAt:"2026-05-03",isAutoGenerated:true},
  {id:"news-12",title:"Coze 2.0 品牌升级：弱化工具属性，强化 AI 工作伙伴定位",summary:"字节跳动旗下 Coze 完成品牌升级，新Logo强调亲和力与陪伴感。同时发布知识库增强、多Agent协作等新功能。",url:"https://www.logonews.cn/coze-new-logo.html",source:"标志情报局",category:"产品发布",publishedAt:"2026-04-22",isAutoGenerated:true},
  {id:"news-13",title:"Cursor vs Windsurf vs GitHub Copilot：2026 AI 编程工具横评",summary:"深度对比三大AI编程工具：Cursor以代码库理解见长，Windsurf主打Agent自主编程，Copilot以生态整合取胜。",url:"#",source:"AI第一站 原创",category:"深度解读",publishedAt:"2026-04-18",isAutoGenerated:true},
  {id:"news-14",title:"Gemini 2.5 Pro 发布：2M 上下文 + 原生多模态，Google 全面反击",summary:"Google 发布 Gemini 2.5 Pro，支持200万token超长上下文，在多项基准测试中超越 GPT-5 和 Claude 4。",url:"https://blog.google/technology/ai/",source:"Google AI Blog",category:"产品发布",publishedAt:"2026-04-15",isAutoGenerated:true},
  {id:"news-15",title:"用 DeepSeek API 搭建免费个人 AI 助手：从注册到上线全流程",summary:"手把手教程：注册DeepSeek → 获取API Key → 安装Chatbox → 配置模型 → 开始使用。全程免费，10分钟搞定。",url:"https://platform.deepseek.com",source:"DeepSeek 开发者平台",category:"教程资源",publishedAt:"2026-04-12",isAutoGenerated:true},
  {id:"news-16",title:"Suno V4 发布：AI 音乐生成进入专业级时代",summary:"Suno V4 大幅提升音质和音乐结构复杂度，支持更精确的风格控制。AI生成音乐正在从'能用'迈向'好听'。",url:"https://suno.com/blog",source:"Suno 官方博客",category:"产品发布",publishedAt:"2026-04-10",isAutoGenerated:true},
  {id:"news-17",title:"即梦 AI 推出 Seedance 2.0：视频生成进入高画质时代",summary:"字节即梦发布 Seedance 2.0 视频生成模型，支持1080p分辨率，画面连贯性和真实感大幅提升。",url:"https://jimeng.jianying.com",source:"即梦 官方",category:"产品发布",publishedAt:"2026-04-08",isAutoGenerated:true},
  {id:"news-18",title:"零基础搭建 AI 客服：Dify + 飞书 完整实战教程",summary:"从零开始：注册Dify → 创建知识库 → 写Agent提示词 → 配置飞书机器人 → 测试上线。全程零代码。",url:"https://docs.dify.ai",source:"Dify 社区",category:"教程资源",publishedAt:"2026-04-05",isAutoGenerated:true},
  {id:"news-19",title:"中国AI产业2026Q1报告：国产大模型进入落地快车道",summary:"2026年Q1，国产AI大模型在政务、金融、医疗等领域加速落地。DeepSeek、Kimi、通义千问等国产模型在中文场景表现已超越国际竞品。",url:"#",source:"AI第一站 综合",category:"行业动态",publishedAt:"2026-04-01",isAutoGenerated:true},
  {id:"news-20",title:"Agent 开发避坑指南：10个新手最常犯的错误",summary:"从Prompt设计到知识库配置，从模型选择到错误处理——整理Agent开发中最常见的10个坑和解决方案。",url:"#",source:"AI第一站 原创",category:"教程资源",publishedAt:"2026-03-28",isAutoGenerated:true},
]
