// AI 新闻资讯数据 —— Agent 自动聚合 + 用户投稿
export interface NewsItem {
  id: string; title: string; summary: string; content: string
  url: string; source: string; category: NewsCategory
  publishedAt: string; importance: number; isAutoGenerated: boolean
  image?: string
}

export type NewsCategory =
  | "行业动态"
  | "产品发布"
  | "教程资源"
  | "深度解读"
  | "开源项目"
  | "政策监管"

export const newsCategories: { key: NewsCategory; label: string }[] = [
  { key: "行业动态", label: "行业动态" },
  { key: "产品发布", label: "产品发布" },
  { key: "教程资源", label: "教程资源" },
  { key: "深度解读", label: "深度解读" },
  { key: "开源项目", label: "开源项目" },
  { key: "政策监管", label: "政策监管" },
]

export const news: NewsItem[] = [
  {
    id: "news-1",
    title: "OpenAI 发布 GPT-5 系列模型，推理能力大幅提升",
    summary: "OpenAI 正式发布 GPT-5 系列，在复杂推理、数学和代码生成方面取得显著进步。新模型支持更长的上下文窗口和更精准的工具调用能力，对 Agent 开发者是重大利好。",
    url: "https://openai.com/index/introducing-gpt-5/",
    source: "OpenAI 官方博客",
    category: "产品发布",
    publishedAt: "2026-05-02",content:"",importance:5,
    isAutoGenerated: true,
  },
  {
    id: "news-2",
    title: "Anthropic 发布 Claude 4，Agent 能力成为核心竞争力",
    summary: "Anthropic 推出 Claude 4 系列，重点强化了 Agent 能力——包括更可靠的多步推理、更精准的工具使用和更强的自主任务执行。Claude 正在从「对话AI」向「行动AI」进化。",
    url: "https://www.anthropic.com/research/claude-4",
    source: "Anthropic 官方",
    category: "产品发布",
    publishedAt: "2026-04-28",content:"",importance:5,
    isAutoGenerated: true,
  },
  {
    id: "news-3",
    title: "Dify 发布 v1.0 正式版，Agent 搭建门槛再降低",
    summary: "开源 LLM 应用平台 Dify 发布 v1.0 正式版，新增可视化多Agent编排、增强的 RAG 引擎、以及一键部署功能。对于想零代码搭建 Agent 的用户，这是目前最成熟的选择。",
    url: "https://dify.ai/blog",
    source: "Dify 官方博客",
    category: "产品发布",
    publishedAt: "2026-05-01",content:"",importance:5,
    isAutoGenerated: true,
  },
  {
    id: "news-4",
    title: "从零到一：如何用 Coze 搭建一个自动客服 Agent（附完整教程）",
    summary: "一篇详细的中文教程，手把手教你用 Coze（扣子）搭建智能客服 Agent。从知识库配置、人设编写、到发布到微信，全程零代码，适合完全没有编程基础的用户。",
    url: "https://www.coze.cn/docs/guides/create_agent",
    source: "Coze 社区",
    category: "教程资源",
    publishedAt: "2026-05-03",content:"",importance:5,
    isAutoGenerated: true,
  },
  {
    id: "news-5",
    title: "DeepSeek 开源新一代模型，推理性能对标国际一线",
    summary: "深度求索开源新一代 DeepSeek 模型，在推理基准测试中表现接近 GPT-5 水平。模型完全开源可商用，对国内 AI 生态是重大利好。许多 AI 导航和 Agent 平台已宣布支持新模型。",
    url: "https://api-docs.deepseek.com/news/news250425",
    source: "DeepSeek 官方",
    category: "开源项目",
    publishedAt: "2026-04-25",
    isAutoGenerated: true,
  },
  {
    id: "news-6",
    title: "OpenClaw 龙虾崛起：从被 Anthropic 封杀到 GitHub 24万星",
    summary: "OpenClaw（龙虾）从2025年11月以 Clawdbot 之名发布，经历 Anthropic 商标投诉、两次更名，如今已成为 GitHub 第二大开源项目。支持12+通讯平台，13000+社区技能包，是Agent时代最具代表性的开源框架。",
    url: "https://github.com/openclaw/openclaw",
    source: "综合报道",
    category: "行业动态",
    publishedAt: "2026-05-04",content:"",importance:5,
    isAutoGenerated: true,
  },
  {
    id: "news-7",
    title: "n8n + AI：把 400 个应用串联起来的自动化工作流",
    summary: "n8n 结合 AI 模块后，可以实现跨应用的智能自动化。本文通过「邮件收到附件 → AI 提取关键信息 → 自动填写表格 → 发送通知」的实际案例，展示了零代码自动化的强大能力。",
    url: "https://blog.n8n.io/ai-automation-workflows/",
    source: "n8n 官方博客",
    category: "教程资源",
    publishedAt: "2026-04-20",
    isAutoGenerated: true,
  },
  {
    id: "news-8",
    title: "Claude Code 安装指南：一条命令搞定 AI 终端编程",
    summary: "Claude Code 是 Anthropic 出品的终端 AI 编程助手，可以直接在命令行中读写文件、管理 Git、调试代码。本文涵盖 Windows/macOS/Linux 三种平台的安装方法，以及认证配置和常用命令。",
    url: "https://developer.aliyun.com/article/1705912",
    source: "阿里云开发者",
    category: "教程资源",
    publishedAt: "2026-05-02",content:"",importance:5,
    isAutoGenerated: true,
  },
  {
    id: "news-9",
    title: "Kimi 月之暗面推出「Kimi+」Agent 功能，支持自定义智能体",
    summary: "Kimi 推出 Agent 功能「Kimi+」，用户可以为特定场景创建专属智能体——比如「论文助手」、「代码审查员」、「旅行规划师」。每个 Agent 可以绑定特定的提示词和知识库，实现专业化的 AI 辅助。",
    url: "https://kimi.moonshot.cn/blog/kimi-plus",
    source: "月之暗面 官方",
    category: "产品发布",
    publishedAt: "2026-05-02",content:"",importance:5,
    isAutoGenerated: true,
  },
  {
    id: "news-10",
    title: "AI 大模型接入全攻略：从 API Key 到本地部署，小白也能看懂",
    summary: "想在自己的应用里接入AI模型？本文从最基础讲起：什么是API Key、怎么获取、不同模型的接入方式和费用对比（OpenAI/Claude/DeepSeek/通义千问），以及用 Dify 一键接入多模型的实操演示。",
    url: "https://docs.dify.ai/guides/model-configuration",
    source: "Dify 官方文档",
    category: "教程资源",
    publishedAt: "2026-05-04",content:"",importance:5,
    isAutoGenerated: true,
  },
  {id:"news-11",title:"微软 Copilot 全面整合 OpenClaw 技术，剑指全天候自主办公",summary:"微软正在探索将 OpenClaw 的自主Agent能力整合进 365 Copilot，打造能7×24小时自主运行的智能办公助手，标志着Agent从辅助工具向自主执行体的转变。",url:"https://ai.zol.com.cn/1165/11652139.html",source:"中关村在线",category:"行业动态",publishedAt:"2026-05-03",content:"",importance:5,isAutoGenerated:true},
  {id:"news-12",title:"Coze 2.0 品牌升级：弱化工具属性，强化 AI 工作伙伴定位",summary:"字节跳动旗下 Coze 完成品牌升级，新Logo强调亲和力与陪伴感。同时发布知识库增强、多Agent协作等新功能。",url:"https://www.logonews.cn/coze-new-logo.html",source:"标志情报局",category:"产品发布",publishedAt:"2026-04-22",content:"",importance:5,isAutoGenerated:true},
  {id:"news-13",title:"Cursor vs Windsurf vs GitHub Copilot：2026 AI 编程工具横评",summary:"深度对比三大AI编程工具：Cursor以代码库理解见长，Windsurf主打Agent自主编程，Copilot以生态整合取胜。",url:"#",source:"AI第一站 原创",category:"深度解读",publishedAt:"2026-04-18",content:"",importance:5,isAutoGenerated:true},
  {id:"news-14",title:"Gemini 2.5 Pro 发布：2M 上下文 + 原生多模态，Google 全面反击",summary:"Google 发布 Gemini 2.5 Pro，支持200万token超长上下文，在多项基准测试中超越 GPT-5 和 Claude 4。",url:"https://blog.google/technology/ai/",source:"Google AI Blog",category:"产品发布",publishedAt:"2026-04-15",content:"",importance:5,isAutoGenerated:true},
  {id:"news-15",title:"用 DeepSeek API 搭建免费个人 AI 助手：从注册到上线全流程",summary:"手把手教程：注册DeepSeek → 获取API Key → 安装Chatbox → 配置模型 → 开始使用。全程免费，10分钟搞定。",url:"https://platform.deepseek.com",source:"DeepSeek 开发者平台",category:"教程资源",publishedAt:"2026-04-12",content:"",importance:5,isAutoGenerated:true},
  {id:"news-16",title:"Suno V4 发布：AI 音乐生成进入专业级时代",summary:"Suno V4 大幅提升音质和音乐结构复杂度，支持更精确的风格控制。AI生成音乐正在从'能用'迈向'好听'。",url:"https://suno.com/blog",source:"Suno 官方博客",category:"产品发布",publishedAt:"2026-04-10",content:"",importance:5,isAutoGenerated:true},
  {id:"news-17",title:"即梦 AI 推出 Seedance 2.0：视频生成进入高画质时代",summary:"字节即梦发布 Seedance 2.0 视频生成模型，支持1080p分辨率，画面连贯性和真实感大幅提升。",url:"https://jimeng.jianying.com",source:"即梦 官方",category:"产品发布",publishedAt:"2026-04-08",content:"",importance:5,isAutoGenerated:true},
  {id:"news-18",title:"零基础搭建 AI 客服：Dify + 飞书 完整实战教程",summary:"从零开始：注册Dify → 创建知识库 → 写Agent提示词 → 配置飞书机器人 → 测试上线。全程零代码。",url:"https://docs.dify.ai",source:"Dify 社区",category:"教程资源",publishedAt:"2026-04-05",content:"",importance:5,isAutoGenerated:true},
  {id:"news-19",title:"中国AI产业2026Q1报告：国产大模型进入落地快车道",summary:"2026年Q1，国产AI大模型在政务、金融、医疗等领域加速落地。DeepSeek、Kimi、通义千问等国产模型在中文场景表现已超越国际竞品。",url:"#",source:"AI第一站 综合",category:"行业动态",publishedAt:"2026-04-01",content:"",importance:5,isAutoGenerated:true},
  {id:"news-20",title:"Agent 开发避坑指南：10个新手最常犯的错误",summary:"从Prompt设计到知识库配置，从模型选择到错误处理——整理Agent开发中最常见的10个坑和解决方案。",url:"#",source:"AI第一站 原创",category:"教程资源",publishedAt:"2026-03-28",content:"",importance:5,isAutoGenerated:true},
  {id:"news-21",title:"全民养龙虾：OpenClaw 引爆中国 AI Agent 普及浪潮",summary:"2026年Q1，OpenClaw日下载量超20万次。ArkClaw/AutoClaw/QClaw等国产套壳如雨后春笋，从极客圈破圈进入大众视野。",url:"#",source:"AI第一站 综合",category:"行业动态",publishedAt:"2026-05-03",content:"",importance:5,isAutoGenerated:true},
  {id:"news-22",title:"工信部发布 OpenClaw 安全风险预警：普通用户如何安全使用Agent",summary:"工信部针对OpenClaw生态发布安全预警。本文整理5条普通用户必做的安全设置：关远程访问、审查技能代码、设API限额等。",url:"#",source:"AI第一站 原创",category:"政策监管",publishedAt:"2026-05-02",content:"",importance:5,isAutoGenerated:true},
  {id:"news-23",title:"QClaw 更新：支持微信企业版接入，稳定性大幅提升",summary:"腾讯QClaw发布v2.3版本，企业微信接入不再掉线，新增10个办公技能。微信个人号接入稳定性也得到改善。",url:"https://qclaw.qq.com",source:"QClaw 官方",category:"产品发布",publishedAt:"2026-05-01",content:"",importance:5,isAutoGenerated:true},
  {id:"news-24",title:"ArkClaw 上线飞书应用商店：一键安装开箱即用",summary:"字节ArkClaw正式上线飞书应用商店，飞书管理员可直接在后台安装。零配置、内置模型、免API Key。",url:"https://www.volcengine.com",source:"火山引擎",category:"产品发布",publishedAt:"2026-04-30",content:"",importance:5,isAutoGenerated:true},
  {id:"news-25",title:"Ollama 0.6 发布：支持多GPU并行推理，速度翻倍",summary:"Ollama最新版支持多GPU并行，本地跑大模型速度翻倍。新增模型管理Web界面，配置更简单。",url:"https://ollama.com/blog",source:"Ollama 官方",category:"产品发布",publishedAt:"2026-04-28",content:"",importance:5,isAutoGenerated:true},
  {id:"news-26",title:"MiniMax M2.5 开源：SWE-Bench得分80.2%逼近Claude Opus",summary:"MiniMax开源M2.5模型，229B总参数仅激活10B。编码测试得分仅差Claude Opus 0.6个百分点，消费级显卡可跑。",url:"https://www.minimaxi.com",source:"MiniMax 官方",category:"开源项目",publishedAt:"2026-04-25",content:"",importance:5,isAutoGenerated:true},
  {id:"news-27",title:"GLM-5.1 发布：744B参数，支持8小时自主编程任务",summary:"智谱发布GLM-5.1，MIT开源。在SWE-Bench Pro自主编程测试中排名第一，可连续8小时完成复杂编程任务。",url:"https://open.bigmodel.cn",source:"智谱 官方",category:"产品发布",publishedAt:"2026-04-22",content:"",importance:5,isAutoGenerated:true},
  {id:"news-28",title:"阿里通义千问推出 Qwen 3.5：支持201种语言，Apache开源",summary:"阿里开源Qwen 3.5，397B总参仅激活17B。支持201种语言和原生多模态，Apache 2.0协议完全商用友好。",url:"https://dashscope.aliyun.com",source:"阿里云",category:"开源项目",publishedAt:"2026-04-20",content:"",importance:5,isAutoGenerated:true},
  {id:"news-29",title:"Llama 4 发布：1M上下文，10M超长版本同期推出",summary:"Meta发布Llama 4系列，Maverick版本1M上下文$0.11/1M tokens历史最低价。Scout版本支持10M上下文。",url:"https://llama.meta.com",source:"Meta AI",category:"产品发布",publishedAt:"2026-04-18",content:"",importance:5,isAutoGenerated:true},
  {id:"news-30",title:"GPT-5.4 正式发布：幻觉减少33%，1M上下文",summary:"OpenAI发布GPT-5.4，综合性能突破新高度。幻觉率降低33%，支持1M超长上下文，API价格降低50%。",url:"https://openai.com/blog",source:"OpenAI",category:"产品发布",publishedAt:"2026-04-15",content:"",importance:5,isAutoGenerated:true},
  {id:"news-31",title:"GPT-5.5 发布：史上最智能模型，SWE-Bench Pro达58.6%",summary:"OpenAI发布GPT-5.5，Terminal-Bench 2.0准确率82.7%。数学能力提升300%，支持200页超长上下文。API输入$5/百万Token。",url:"https://openai.com/blog",source:"OpenAI",category:"产品发布",publishedAt:"2026-05-03",content:"",importance:5,isAutoGenerated:true},
  {id:"news-32",title:"Meta Llama 4 开源：MoE架构，89.7% MMLU超越GPT-4",summary:"Meta发布Llama 4 Mini/Base/Ultra三版本。Ultra版MMLU得分89.7%超越GPT-4，推理仅激活220亿参数大幅降低部署成本。",url:"https://llama.meta.com",source:"Meta AI",category:"开源项目",publishedAt:"2026-05-03",content:"",importance:5,isAutoGenerated:true},
  {id:"news-33",title:"OpenAI发布GPT-5.5-Cyber：专为网络安全设计的大模型",summary:"GPT-5.5-Cyber恶意代码识别准确率提升28%，面向全球核心网络安全机构开放。AI安全成为独立赛道。",url:"https://openai.com/blog",source:"OpenAI",category:"产品发布",publishedAt:"2026-05-04",content:"",importance:5,isAutoGenerated:true},
  {id:"news-34",title:"国内大模型密集发布：Kimi K2.6、Qwen3.6、DeepSeek V4 Pro同期登场",summary:"4月底5月初国内大厂密集发模：Kimi K2.6可13小时不间断编码，Qwen3.6 27B/35B开源，DeepSeek V4 Pro发布。",url:"#",source:"AI第一站 综合",category:"行业动态",publishedAt:"2026-05-04",content:"",importance:5,isAutoGenerated:true},
  {id:"news-35",title:"GitHub Copilot X 新增AI代码审查，Bug检出率提升35%",summary:"GitHub推出Copilot X代码审查功能，审查时间减少60%，Bug检出率提升35%。开发者工具进入AI审查时代。",url:"https://github.com/features/preview",source:"GitHub",category:"产品发布",publishedAt:"2026-05-02",content:"",importance:5,isAutoGenerated:true},
  {id:"news-36",title:"Dify获3000万美元Pre-A融资，全球部署超140万台",summary:"开源LLM应用平台Dify完成3000万美元Pre-A轮融资，全球部署超140万台机器。零代码Agent搭建继续降低门槛。",url:"https://dify.ai/blog",source:"Dify",category:"行业动态",publishedAt:"2026-05-01",content:"",importance:5,isAutoGenerated:true},
  {id:"news-37",title:"Claude Opus 4.7 接入：代码生成和对齐能力再突破",summary:"B.AI正式接入Claude Opus 4.7，在代码生成、逻辑对齐与复杂任务执行方面表现突出。",url:"https://console.anthropic.com",source:"Anthropic",category:"产品发布",publishedAt:"2026-05-01",content:"",importance:5,isAutoGenerated:true},
  {id:"news-38",title:"微软推法律AI助手：用确定性算法替代大模型自由发挥",summary:"微软专为法律人推出AI助手，智能审查合同、极速比对版本、追踪修订。标志通用AI向垂直专业AI转向。",url:"https://news.microsoft.com",source:"微软",category:"行业动态",publishedAt:"2026-04-30",content:"",importance:5,isAutoGenerated:true},
  {id:"news-39",title:"2026 AI算力大战：四大巨头年投入超7200亿美元",summary:"Alphabet、亚马逊、微软、Meta2026年资本支出合计超7200亿美元。日均Token调用量从万亿增长至100万亿。",url:"#",source:"综合报道",category:"行业动态",publishedAt:"2026-05-01",content:"",importance:5,isAutoGenerated:true},
  {id:"news-40",title:"特斯拉Optimus Gen-3量产：具身智能进入制造阶段",summary:"特斯拉Optimus Gen-3 Q2启动量产，搭载FSD纯视觉AI大模型。Figure 03实现一小时一台生产节拍。",url:"#",source:"综合报道",category:"行业动态",publishedAt:"2026-05-02",content:"",importance:5,isAutoGenerated:true},
]
